openapi: 3.0.0
info:
  title: Sample API
  description: sample api.
  version: 0.1.9

paths:
  /sum:
    post:
      summary: calculate
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
          
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:012345678901:function:PostSamplePetFunction/invocations
        responses:
          default:
            statusCode: "200"
        type: "AWS"