AWSTemplateFormatVersion : "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: sample API Service

Resources:
  PostSampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostSamplePetFunction
      Runtime: python3.8
      Handler: lambda_function.lambda_handler
      CodeUri: ./function/
      Events:
        PostSampleApi:
          Type: Api
          Properties:
            RestApiId: !Ref SampleApiGateway
            Path: /sum
            Method: POST
      Policies:
        - AWSLambdaBasicExecutionRole
  SampleApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: ./swagger.yaml
Outputs:
# Sum Outputs
  SumFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for SumFunction"
    Value: !Sub "https://${SampleApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/sum"